### ISSUE TITLE
Game still don't recognise mods.

### ISSUE THREAD

**Issue by lsnmateuszp** [MCOfficer/sgmm#1]
Done everything according to instruction. But my question is, what should i do with this?:

Open the Launcher once to regenerate it; until then, Stellaris won't recognize your mods.

GOG Stellaris is isntalled via sh scripts, there is no launcher here.

**Comment by lsnmateuszp** [comment]
Sorry, got it working! 
inside game there is ./dowser to run launcher.
EVERYTHING works perfectly, thank You!!

**Comment by MCOfficer** [comment]
Yeah, the GOG version is very weird. in my case, there is a script called something like `bootstrap-v2` that starts the launcher.
